# Generated by Django 2.1.2 on 2018-10-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('image', models.TextField()),
                ('description', models.TextField()),
                ('drand', models.TextField()),
                ('type1', models.TextField()),
                ('price', models.FloatField()),
                ('amount_present', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('rate', models.IntegerField()),
                ('review', models.TextField()),
                ('user_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Waiting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('user', models.TextField()),
                ('status', models.TextField()),
            ],
        ),
    ]
