# Generated by Django 2.1.2 on 2018-11-01 19:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(default='None', max_length=50),
            preserve_default=False,
        ),
    ]
