# Generated by Django 2.1.2 on 2018-11-18 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='review',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='amount_in_basket',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
