# Generated by Django 2.1.2 on 2018-11-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_auto_20181106_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.IntegerField(default=0),
        ),
    ]
