# Generated by Django 2.1.2 on 2018-11-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_product_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
