# Generated by Django 2.1.2 on 2018-11-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_product_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_transit',
            field=models.IntegerField(default=1),
        ),
    ]
