# Generated by Django 2.1.2 on 2018-11-11 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_product_is_transit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
    ]
