# Generated by Django 2.1.2 on 2018-11-12 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_remove_product_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='amount_present',
            new_name='amount_in_basket',
        ),
    ]
